import BaseSeeder from '@ioc:Adonis/Lucid/Seeder';
import Address from 'App/Models/Address';
import Client from 'App/Models/Client';
import Phone from 'App/Models/Phone';
import Product from 'App/Models/Product';
import ProductBrand from 'App/Models/ProductBrand';
import ProductCategory from 'App/Models/ProductCategory';
import Purchase from 'App/Models/Purchase';
import { DateTime } from 'luxon';

export default class InitialSeeder extends BaseSeeder {
  public async run() {
    await ProductCategory.createMany([
      { categoryName: 'Eletrônicos' },
      { categoryName: 'Roupas' },
      { categoryName: 'Livros' },
      { categoryName: 'Casa e Jardim' },
      { categoryName: 'Esportes' },
      { categoryName: 'Beleza' },
      { categoryName: 'Brinquedos' },
      { categoryName: 'Automotivo' },
      { categoryName: 'Alimentos' },
      { categoryName: 'Saúde' },
    ]);
    await ProductBrand.createMany([
      { brandName: 'Samsung' },
      { brandName: 'Nike' },
      { brandName: 'Sony' },
      { brandName: 'Apple' },
      { brandName: 'Adidas' },
      { brandName: 'LG' },
      { brandName: 'Microsoft' },
      { brandName: 'Puma' },
      { brandName: 'Philips' },
      { brandName: 'Hewlett-Packard' },
    ]);
    await Product.createMany([
      {
        name: 'Smartphone Galaxy S20',
        price: 2899.99,
        description: 'Último lançamento da Samsung.',
        categoryId: 1,
        brandId: 1,
        stock: 50,
      },
      {
        name: 'Tênis de Corrida Air Zoom Pegasus 38',
        price: 699.9,
        description: 'Tênis de corrida de alta performance.',
        categoryId: 5,
        brandId: 2,
        stock: 100,
      },
      {
        name: 'Livro - A Arte da Guerra',
        price: 29.9,
        description: 'Clássico da estratégia militar.',
        categoryId: 3,
        brandId: 1,
        stock: 30,
      },
      {
        name: 'Notebook MacBook Pro',
        price: 10999.99,
        description: 'Potência e elegância em um só produto.',
        categoryId: 1,
        brandId: 4,
        stock: 20,
      },
      {
        name: 'Smart TV LED 4K 55" LG',
        price: 2999.0,
        description: 'Qualidade de imagem incrível para sua sala.',
        categoryId: 4,
        brandId: 6,
        stock: 15,
      },
      {
        name: 'Camiseta Adidas Originals',
        price: 99.9,
        description: 'Conforto e estilo para o dia a dia.',
        categoryId: 2,
        brandId: 5,
        stock: 200,
      },
      {
        name: 'Geladeira Brastemp Inverse',
        price: 4999.0,
        description: 'Design moderno e eficiência energética.',
        categoryId: 4,
        brandId: 7,
        stock: 10,
      },
      {
        name: 'Console Xbox Series X',
        price: 3499.99,
        description: 'Experiência de jogo de próxima geração.',
        categoryId: 1,
        brandId: 7,
        stock: 30,
      },
      {
        name: 'Perfume Chanel Nº 5',
        price: 499.9,
        description: 'Fragrância clássica e elegante.',
        categoryId: 6,
        brandId: 8,
        stock: 50,
      },
      {
        name: 'Panela Elétrica Philips Walita',
        price: 399.0,
        description: 'Praticidade na cozinha com alta qualidade.',
        categoryId: 4,
        brandId: 9,
        stock: 25,
      },
    ]);
    await Client.createMany([
      {
        name: 'João Silva',
        cpf: '12345678900',
        sex: 'Masculino',
        birthdate: DateTime.fromISO('1990-05-15'),
      },
      {
        name: 'Maria Santos',
        cpf: '98765432100',
        sex: 'Feminino',
        birthdate: DateTime.fromISO('1985-10-20'),
      },
      {
        name: 'Pedro Oliveira',
        cpf: '45678912300',
        sex: 'Masculino',
        birthdate: DateTime.fromISO('1995-03-25'),
      },
      {
        name: 'Ana Souza',
        cpf: '78912345600',
        sex: 'Feminino',
        birthdate: DateTime.fromISO('1988-12-10'),
      },
      {
        name: 'Lucas Pereira',
        cpf: '32165498700',
        sex: 'Masculino',
        birthdate: DateTime.fromISO('1992-07-05'),
      },
      {
        name: 'Juliana Costa',
        cpf: '65432178900',
        sex: 'Feminino',
        birthdate: DateTime.fromISO('1993-09-30'),
      },
      {
        name: 'Márcio Santos',
        cpf: '23456789000',
        sex: 'Masculino',
        birthdate: DateTime.fromISO('1987-04-12'),
      },
      {
        name: 'Carla Oliveira',
        cpf: '87654321000',
        sex: 'Feminino',
        birthdate: DateTime.fromISO('1991-11-08'),
      },
      {
        name: 'Fernanda Lima',
        cpf: '54321098700',
        sex: 'Feminino',
        birthdate: DateTime.fromISO('1994-02-28'),
      },
      {
        name: 'Rafael Almeida',
        cpf: '76543210900',
        sex: 'Masculino',
        birthdate: DateTime.fromISO('1986-06-18'),
      },
    ]);
    await Phone.createMany([
      {
        phoneNumber: '1112345678',
        clientId: 1,
      },
      {
        phoneNumber: '2198765432',
        clientId: 2,
      },
      {
        phoneNumber: '4145678901',
        clientId: 3,
      },
      {
        phoneNumber: '5123456789',
        clientId: 4,
      },
      {
        phoneNumber: '2187654321',
        clientId: 5,
      },
      {
        phoneNumber: '2154321098',
        clientId: 6,
      },
      {
        phoneNumber: '1176543210',
        clientId: 7,
      },
      {
        phoneNumber: '5132109876',
        clientId: 8,
      },
      {
        phoneNumber: '1165432109',
        clientId: 9,
      },
      {
        phoneNumber: '4198765432',
        clientId: 10,
      },
    ]);
    await Address.createMany([
      {
        address: 'Rua A, 123',
        number: '123',
        complement: 'Apto 101',
        neighborhood: 'Centro',
        zipCode: '12345-678',
        city: 'São Paulo',
        state: 'SP',
        country: 'Brasil',
        clientId: 1,
      },
      {
        address: 'Av. B, 456',
        number: '456',
        complement: '',
        neighborhood: 'Jardins',
        zipCode: '98765-432',
        city: 'Rio de Janeiro',
        state: 'RJ',
        country: 'Brasil',
        clientId: 2,
      },
      {
        address: 'Rua C, 789',
        number: '789',
        complement: '',
        neighborhood: 'Boa Vista',
        zipCode: '45678-901',
        city: 'Curitiba',
        state: 'PR',
        country: 'Brasil',
        clientId: 3,
      },
      {
        address: 'Av. D, 987',
        number: '987',
        complement: 'Sala 202',
        neighborhood: 'Centro',
        zipCode: '23456-789',
        city: 'Porto Alegre',
        state: 'RS',
        country: 'Brasil',
        clientId: 4,
      },
      {
        address: 'Rua E, 321',
        number: '321',
        complement: '',
        neighborhood: 'Copacabana',
        zipCode: '87654-321',
        city: 'Rio de Janeiro',
        state: 'RJ',
        country: 'Brasil',
        clientId: 5,
      },
      {
        address: 'Av. F, 654',
        number: '654',
        complement: 'Apto 501',
        neighborhood: 'Barra da Tijuca',
        zipCode: '54321-098',
        city: 'Rio de Janeiro',
        state: 'RJ',
        country: 'Brasil',
        clientId: 6,
      },
      {
        address: 'Rua G, 234',
        number: '234',
        complement: '',
        neighborhood: 'Centro',
        zipCode: '76543-210',
        city: 'São Paulo',
        state: 'SP',
        country: 'Brasil',
        clientId: 7,
      },
      {
        address: 'Av. H, 567',
        number: '567',
        complement: '',
        neighborhood: 'Centro',
        zipCode: '32109-876',
        city: 'Porto Alegre',
        state: 'RS',
        country: 'Brasil',
        clientId: 8,
      },
      {
        address: 'Rua I, 876',
        number: '876',
        complement: 'Casa 1',
        neighborhood: 'Jardim América',
        zipCode: '65432-109',
        city: 'São Paulo',
        state: 'SP',
        country: 'Brasil',
        clientId: 9,
      },
      {
        address: 'Av. J, 210',
        number: '210',
        complement: '',
        neighborhood: 'Boa Vista',
        zipCode: '98765-432',
        city: 'Curitiba',
        state: 'PR',
        country: 'Brasil',
        clientId: 10,
      },
    ]);
    await Purchase.createMany([
      {
        quantity: 2,
        unitPrice: 2899.99,
        totalPrice: 5799.98,
        date: DateTime.fromISO('2024-06-29'),
        time: DateTime.fromISO('15:30:00'),
        clientId: 1,
        productId: 1,
      },
      {
        quantity: 1,
        unitPrice: 699.9,
        totalPrice: 699.9,
        date: DateTime.fromISO('2024-06-28'),
        time: DateTime.fromISO('10:45:00'),
        clientId: 2,
        productId: 2,
      },
      {
        quantity: 3,
        unitPrice: 29.9,
        totalPrice: 89.7,
        date: DateTime.fromISO('2024-06-27'),
        time: DateTime.fromISO('14:00:00'),
        clientId: 3,
        productId: 3,
      },
      {
        quantity: 1,
        unitPrice: 10999.99,
        totalPrice: 10999.99,
        date: DateTime.fromISO('2024-06-26'),
        time: DateTime.fromISO('18:20:00'),
        clientId: 4,
        productId: 4,
      },
      {
        quantity: 2,
        unitPrice: 2999.0,
        totalPrice: 5998.0,
        date: DateTime.fromISO('2024-06-25'),
        time: DateTime.fromISO('12:15:00'),
        clientId: 5,
        productId: 5,
      },
      {
        quantity: 5,
        unitPrice: 99.9,
        totalPrice: 499.5,
        date: DateTime.fromISO('2024-06-24'),
        time: DateTime.fromISO('09:00:00'),
        clientId: 6,
        productId: 6,
      },
      {
        quantity: 1,
        unitPrice: 4999.0,
        totalPrice: 4999.0,
        date: DateTime.fromISO('2024-06-23'),
        time: DateTime.fromISO('16:40:00'),
        clientId: 7,
        productId: 7,
      },
      {
        quantity: 4,
        unitPrice: 3499.99,
        totalPrice: 13999.96,
        date: DateTime.fromISO('2024-06-22'),
        time: DateTime.fromISO('11:30:00'),
        clientId: 8,
        productId: 8,
      },
      {
        quantity: 1,
        unitPrice: 499.9,
        totalPrice: 499.9,
        date: DateTime.fromISO('2024-06-21'),
        time: DateTime.fromISO('13:20:00'),
        clientId: 9,
        productId: 9,
      },
      {
        quantity: 2,
        unitPrice: 399.0,
        totalPrice: 798.0,
        date: DateTime.fromISO('2024-06-20'),
        time: DateTime.fromISO('17:00:00'),
        clientId: 10,
        productId: 10,
      },
    ]);
  }
}
