services:
  db:
    image: mysql:8.0.32
    volumes:
      - .database/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=ecommerce
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
